version: '3'

# https://docs.docker.com/compose/compose-file/

services:

  prosody:
    image: vodolaz095/prosody:latest
    ports:
      - '5222:5222'
      - '5269:5269'
    volumes:
      - /opt/dockervolumes/prosody/config:/etc/prosody:Z
      - /var/lib/prosody:/var/lib/prosody:Z
      - /var/log/prosody:/var/log/prosody:Z
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == holod]
